AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Layout/AlignHash:
  EnforcedColonStyle: table